### PR TITLE
Easy framework for analyzing decentralized optimization methods with PESTO

### PR DESCRIPTION
**Pull request by sebcolla**

### CODE REVIEW

**Comment by AdrienTaylor** [comment]
Hello,
Minor requested changes:
- please remove the *.asv from the DGD example folder
- I get a warning with the new version of Install_PESTO.m -> necessary to savepath? Mb add an option in the install file (save path or not; default should be "no", I find the "automatic yes" a bit invasive). (Error message: "Warning: Unable to save path to file '/usr/local/MATLAB/R2020b/toolbox/local/pathdef.m'. You can save your path to a
different location by calling SAVEPATH with an input argument that specifies the full path. For MATLAB to use that path in
future sessions, save the path to 'pathdef.m' in your MATLAB startup folder. ")
- in the "verbose messages": "LMIs constraints (done, 303 constraint(s) added (included 3 LMIs) " --> included -> including, and missing parentheses in the text. (example DGD)
- Example DGD: possible to structure a bit more the example? uniformize the comments+ make clear what we should comment for relaxed version VS exact version (currently, e.g., N is in the same block as that of the relaxed version so a user might comment it blindly, whereas it needs to be defined in both cases). Also, maybe put a bit of space in the description of the example, and separate the text in two parts for the two different cases?
Beyond that, everything seems very nice!

**Comment by sebcolla** [comment]
Hello Adrien,

Thank you for your review. I will implement all the requested changes.

**Comment by sebcolla** [comment]
I think everything is fine now. Could you check my changes when you have time?
Thank you.

**Comment by AdrienTaylor** [comment]
Hello,

Still a few minor points:
- in verbose mode: LMIs constraints -> LMI constraints
- in the userguide:
    "New auxiliary functions and methods in pep class helping to write easily many decentralized optimization algorithm with PESTO . It allows to consider all agents at once in the operations, which makes the formulations more compact and clear. See an example in Examples/11/A."
    -> I disagree with the "many": either you indeed show many examples, or you remove it.
Suggestion (also with a few lang. improvements):
    "New auxiliary functions and methods tailored for simplifying the writing of decentralized gradient-type methods
    within PESTO. Those new functions allow considering all agents at once in the operations, instead of having to
    implement multiple loops for modelling the network. See Examples/11/A."
- For the other update, suggestion:
    "Creation of the Matrix class for representing consensus matrices within a PEP. The goal is to simplify the writing of
    decentralized gradient-type methods."
    
Thanks in advance!

**Pull request merged**
